// packages/react-test-app/src/preview-examples/action-card.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { iconRefresh } from '@irisieason/ix-icons/icons';
import { IxActionCard } from '@siemens/ix-react';

export default () => {
  return (
    <IxActionCard
      icon={iconRefresh}
      heading="Scan for new devices"
      subheading="Secondary text"
      variant="outline"
      onClick={console.log}
    ></IxActionCard>
  );
};

// packages/vue-test-app/src/preview-examples/action-card.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxActionCard } from '@irisieason/ix-vue';
import { iconRefresh } from '@irisieason/ix-icons/icons';

const onClick = (event: Event) => {
  console.log(event);
};
</script>

<template>
  <IxActionCard
    :icon="iconRefresh"
    heading="Scan for new devices"
    subheading="Secondary text"
    variant="outline"
    @click="onClick"
  ></IxActionCard>
</template>
