// packages/react-test-app/src/preview-examples/button-group.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxButton } from '@irisieason/ix-react';

export default () => (
  <div className="ix-button-group">
    <IxButton variant="subtle-secondary">Button 1</IxButton>
    <IxButton> Button 2 </IxButton>
    <IxButton variant="subtle-secondary">Button 3</IxButton>
    <IxButton variant="subtle-secondary">Button 4</IxButton>
  </div>
);

// packages/vue-test-app/src/preview-examples/button-group.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxButton } from '@irisieason/ix-vue';
</script>

<template>
  <div class="ix-button-group">
    <IxButton variant="subtle-secondary"> Button 1 </IxButton>
    <IxButton> Button 2 </IxButton>
    <IxButton variant="subtle-secondary"> Button 3 </IxButton>
    <IxButton variant="subtle-secondary"> Button 4 </IxButton>
  </div>
</template>
