// packages/react-test-app/src/preview-examples/event-list-compact.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxEventList, IxEventListItem } from '@irisieason/ix-react';

export default () => {
  return (
    <IxEventList compact>
      <IxEventListItem itemColor="color-primary">Text 1</IxEventListItem>
      <IxEventListItem itemColor="color-primary">Text 2</IxEventListItem>
      <IxEventListItem itemColor="color-primary">Text 3</IxEventListItem>
      <IxEventListItem itemColor="color-primary">Text 4</IxEventListItem>
    </IxEventList>
  );
};

// packages/vue-test-app/src/preview-examples/event-list-compact.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxEventList, IxEventListItem } from '@irisieason/ix-vue';
</script>

<template>
  <IxEventList compact>
    <IxEventListItem itemColor="color-primary">Text 1</IxEventListItem>
    <IxEventListItem itemColor="color-primary">Text 2</IxEventListItem>
    <IxEventListItem itemColor="color-primary">Text 3</IxEventListItem>
    <IxEventListItem itemColor="color-primary">Text 4</IxEventListItem>
  </IxEventList>
</template>
