// packages/react-test-app/src/preview-examples/expanding-search.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxExpandingSearch } from '@irisieason/ix-react';

export default () => {
  return <IxExpandingSearch placeholder="Search..."></IxExpandingSearch>;
};

// packages/vue-test-app/src/preview-examples/expanding-search.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxExpandingSearch } from '@irisieason/ix-vue';
</script>

<template>
  <IxExpandingSearch placeholder="Search..."></IxExpandingSearch>
</template>
