// packages/angular-test-app/src/preview-examples/form-checkbox-validation.ts
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  standalone: false,
  selector: 'app-example',
  templateUrl: `./form-checkbox-validation.html`,
})
export default class FormCheckboxValidation {}

// packages/vue-test-app/src/preview-examples/form-checkbox-validation.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxCheckbox, IxCheckboxGroup } from '@irisieason/ix-vue';
</script>

<template>
  <div class="checkbox-group-wrapper">
    <IxCheckboxGroup label="Terms of something" info-text="Info text">
      <IxCheckbox
        label="I agree everything"
        name="agreed"
        class="ix-info"
      ></IxCheckbox>
    </IxCheckboxGroup>
  </div>

  <div class="checkbox-group-wrapper">
    <IxCheckboxGroup label="Terms of something" warning-text="Warning text">
      <IxCheckbox
        label="I agree everything"
        name="agreed"
        class="ix-warning"
      ></IxCheckbox>
      <IxCheckbox
        label="I disagree everything"
        name="agreed"
        class="ix-warning"
      ></IxCheckbox>
    </IxCheckboxGroup>
  </div>

  <div class="checkbox-group-wrapper">
    <IxCheckboxGroup label="Terms of something" invalid-text="Invalid text">
      <IxCheckbox
        label="I agree everything"
        name="agreed"
        class="ix-invalid"
      ></IxCheckbox>
      <IxCheckbox
        label="I disagree everything"
        name="agreed"
        class="ix-invalid"
      ></IxCheckbox>
    </IxCheckboxGroup>
  </div>

  <div class="checkbox-group-wrapper">
    <IxCheckboxGroup label="Terms of something" valid-text="Valid text">
      <IxCheckbox
        label="I agree everything"
        name="agreed"
        class="ix-valid"
      ></IxCheckbox>
      <IxCheckbox
        label="I disagree everything"
        name="agreed"
        class="ix-valid"
      ></IxCheckbox>
    </IxCheckboxGroup>
  </div>
</template>

<style scoped>
.checkbox-group-wrapper {
  margin-bottom: 1rem;
}
</style>
