// packages/react-test-app/src/preview-examples/loading.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { ModalLoadingContext } from '@irisieason/ix';
import { IxButton, showModalLoading } from '@irisieason/ix-react';

export default () => {
  const startLoading = () => {
    let count = 0;
    const progress: ModalLoadingContext = showModalLoading('Loading 0/2');
    const interval = setInterval(() => {
      count++;
      progress.update(`Loading ${count}/2`);

      if (count === 2) {
        progress.finish('Done');
        clearInterval(interval);
      }
    }, 1000);
  };
  return <IxButton onClick={() => startLoading()}>Start loading</IxButton>;
};

// packages/vue-test-app/src/preview-examples/loading.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxButton, showModalLoading } from '@irisieason/ix-vue';
import { ModalLoadingContext } from '@irisieason/ix';

const startLoading = () => {
  let count = 0;
  const progress: ModalLoadingContext = showModalLoading('Loading 0/2');
  const interval = setInterval(() => {
    count++;
    progress.update(`Loading ${count}/2`);

    if (count === 2) {
      progress.finish('Done');
      clearInterval(interval);
    }
  }, 1000);
};
</script>

<template>
  <IxButton @click="startLoading">Start loading</IxButton>
</template>
