// packages/react-test-app/src/preview-examples/modal-sizes.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import './modal-sizes.scoped.css';

import { IxModalSize } from '@irisieason/ix';
import { IxButton, Modal, ModalRef, showModal } from '@irisieason/ix-react';
import { useRef } from 'react';

export default () => {
  const modalRef = useRef<ModalRef>(null);

  const open = (size: IxModalSize) => {
    showModal({
      size: size,
      content: (
        <Modal ref={modalRef}>
          <IxButton onClick={() => modalRef.current?.close(null)}>
            Modal with size {size}
          </IxButton>
        </Modal>
      ),
    });
  };

  return (
    <div className="modal-sizes">
      <IxButton onClick={() => open('360')}>Show modal size 360</IxButton>
      <IxButton onClick={() => open('480')}>Show modal size 480</IxButton>
      <IxButton onClick={() => open('600')}>Show modal size 600</IxButton>
      <IxButton onClick={() => open('720')}>Show modal size 720</IxButton>
      <IxButton onClick={() => open('840')}>Show modal size 840</IxButton>
      <IxButton onClick={() => open('full-width')}>
        Show modal size full-width
      </IxButton>
      <IxButton onClick={() => open('full-screen')}>
        Show modal size full-screen
      </IxButton>
    </div>
  );
};

// packages/vue-test-app/src/preview-examples/modal-sizes.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="tsx">
import type { IxModalSize } from '@irisieason/ix';
import {
  IxButton,
  Modal,
  type ModalSlotProps,
  showModal,
} from '@irisieason/ix-vue';

const sizes: IxModalSize[] = [
  '360',
  '480',
  '600',
  '720',
  '840',
  'full-width',
  'full-screen',
];

const open = (size: IxModalSize) => {
  showModal({
    size,
    content: (
      <Modal>
        {({ closeModal }: ModalSlotProps) => (
          <IxButton onClick={closeModal}> Modal with size {size} </IxButton>
        )}
      </Modal>
    ),
  });
};
</script>

<style scoped src="./modal-sizes.css"></style>

<template>
  <div class="modal-sizes">
    <IxButton v-for="size in sizes" :key="size" @click="open(size)">
      Show modal size {{ size }}
    </IxButton>
  </div>
</template>
