// packages/angular-standalone-test-app/src/preview-examples/number-input-label.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';
import {
  IxNumberInput,
  IxTextValueAccessorDirective,
} from '@irisieason/ix-angular/standalone';

@Component({
  selector: 'app-example',
  imports: [IxNumberInput, IxTextValueAccessorDirective],
  templateUrl: './number-input-label.html',
})
export default class NumberInputLabel {}

// packages/vue-test-app/src/preview-examples/number-input-label.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxNumberInput } from '@irisieason/ix-vue';
</script>

<template>
  <IxNumberInput
    label="Some label"
    helper-text="Some helper text"
  ></IxNumberInput>
</template>
