// packages/react-test-app/src/preview-examples/progress-indicator.tsx
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { IxProgressIndicator } from '@irisieason/ix-react';
import './progress-indicator.scoped.css';

export default () => {
  return (
    <IxProgressIndicator
      label="Download"
      value={75}
      helper-text="This is a help text for the progress indicator"
    >
      75%
    </IxProgressIndicator>
  );
};

// packages/vue-test-app/src/preview-examples/progress-indicator.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxProgressIndicator } from '@irisieason/ix-vue';
</script>

<style scoped src="./progress-indicator.css"></style>

<template>
  <IxProgressIndicator
    label="Download"
    :value="75"
    helper-text="This is a help text for the progress indicator"
  >
    75%
  </IxProgressIndicator>
</template>
