// packages/react-test-app/src/preview-examples/select-validation.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxSelect, IxSelectItem } from '@irisieason/ix-react';

export default () => {
  return (
    <>
      <div>
        <IxSelect
          label="Framework options"
          name="framework-option"
          infoText="We will show examples based on your selection."
          className="ix-info"
        >
          <IxSelectItem value="angular" label="Angular"></IxSelectItem>
          <IxSelectItem value="react" label="React"></IxSelectItem>
          <IxSelectItem value="vue" label="Vue"></IxSelectItem>
        </IxSelect>
      </div>
      <div>
        <IxSelect
          label="Framework options"
          name="framework-option"
          warningText="Selected Framework is partly supported."
          className="ix-warning"
          value="blazor"
        >
          <IxSelectItem value="blazor" label="Blazor"></IxSelectItem>
          <IxSelectItem value="nextjs" label="NextJS"></IxSelectItem>
        </IxSelect>
      </div>
      <div>
        <IxSelect
          label="Framework options"
          name="framework-option"
          validText="Selected Framework is fully supported."
          className="ix-valid"
          value="angular"
        >
          <IxSelectItem value="angular" label="Angular"></IxSelectItem>
          <IxSelectItem value="react" label="React"></IxSelectItem>
          <IxSelectItem value="vue" label="Vue"></IxSelectItem>
        </IxSelect>
      </div>
      <div>
        <IxSelect
          label="Framework options"
          name="framework-option"
          invalidText="Selected Framework is not supported."
          className="ix-invalid"
          value="svelte"
        >
          <IxSelectItem value="svelte" label="Svelte"></IxSelectItem>
          <IxSelectItem value="solid" label="Solid"></IxSelectItem>
        </IxSelect>
      </div>
    </>
  );
};

// packages/vue-test-app/src/preview-examples/select-validation.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxSelect, IxSelectItem } from '@irisieason/ix-vue';
</script>

<template>
  <div>
    <IxSelect
      label='Framework options'
      name='framework-option'
      info-text='We will show examples based on your selection.'
      class='ix-info'
    >
      <IxSelectItem value='angular' label='Angular'></IxSelectItem>
      <IxSelectItem value='react' label='React'></IxSelectItem>
      <IxSelectItem value='vue' label='Vue'></IxSelectItem>
    </IxSelect>
  </div>
  <div>
    <IxSelect
      label='Framework options'
      name='framework-option'
      warning-text='Selected Framework is partly supported.'
      class='ix-warning'
      value='blazor'
    >
      <IxSelectItem value='blazor' label='Blazor'></IxSelectItem>
      <IxSelectItem value='nextjs' label='NextJS'></IxSelectItem>
    </IxSelect>
  </div>
  <div>
    <IxSelect
      label='Framework options'
      name='framework-option'
      valid-text='Selected Framework is fully supported.'
      class='ix-valid'
      value='angular'
    >
      <IxSelectItem value='angular' label='Angular'></IxSelectItem>
      <IxSelectItem value='react' label='React'></IxSelectItem>
      <IxSelectItem value='vue' label='Vue'></IxSelectItem>
    </IxSelect>
  </div>
  <div>
    <IxSelect
      label='Framework options'
      name='framework-option'
      invalid-text='Selected Framework is not supported.'
      class='ix-invalid'
      value='svelte'
    >
      <IxSelectItem value='svelte' label='Svelte'></IxSelectItem>
      <IxSelectItem value='solid' label='Solid'></IxSelectItem>
    </IxSelect>
  </div>
</template>
