// packages/react-test-app/src/preview-examples/spinner.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxSpinner } from '@irisieason/ix-react';

export default () => {
  return <IxSpinner></IxSpinner>;
};

// packages/vue-test-app/src/preview-examples/spinner.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxSpinner } from '@irisieason/ix-vue';
</script>

<template>
  <IxSpinner></IxSpinner>
</template>
