// packages/angular-standalone-test-app/src/preview-examples/tile.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';
import {
  IxTile,
  IxIconButton,
  IxButton,
  IxIcon,
} from '@irisieason/ix-angular/standalone';

@Component({
  selector: 'app-example',
  imports: [IxTile, IxIconButton, IxButton, IxIcon],
  template: `
    <ix-tile size="small">92.8 °C</ix-tile>

    <ix-tile size="medium">
      <div slot="header">Tile header</div>
      <div class="text-l">92.8 °C</div>
    </ix-tile>

    <ix-tile size="big">
      <div class="tile-header" slot="header">
        Tile header
        <ix-icon-button variant="tertiary" icon="context-menu"></ix-icon-button>
      </div>
      <div slot="subheader">Temperature</div>
      <div
        style="
        display: flex;
        flex-direction: column;
        height: 100%;
        align-items: flex-end;
        justify-content: space-between;
      "
      >
        <span>92.8 °C</span>
      </div>
      <div class="tile-footer" slot="footer">
        <ix-button variant="tertiary" slot="footer">
          <ix-icon name="chevron-right-small"></ix-icon>Details
        </ix-button>
      </div>
    </ix-tile>
  `,
  styleUrls: ['./tile.css'],
})
export default class Tile {}

// packages/vue-test-app/src/preview-examples/tile.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import {
  iconChevronRightSmall,
  iconContextMenu,
} from '@irisieason/ix-icons/icons';
import { IxButton, IxIconButton, IxTile } from '@irisieason/ix-vue';
</script>

<style scoped src="./tile.css"></style>

<template>
  <div className="example">
    <IxTile size="small">92.8 °C</IxTile>

    <IxTile size="medium">
      <div slot="header">Tile header</div>
      <div className="text-l">92.8 °C</div>
    </IxTile>

    <IxTile size="big">
      <div className="tile-header" slot="header">
        Tile header
        <IxIconButton variant="tertiary" :icon="iconContextMenu"></IxIconButton>
      </div>
      <div slot="subheader">Temperature</div>
      <div
        style="
          display: flex;
          flex-direction: column;
          height: 100%;
          align-items: flex-end;
          justify-content: space-between;
        "
      >
        <span>92.8 °C</span>
      </div>
      <div className="tile-footer" slot="footer">
        <IxButton variant="tertiary" :icon="iconChevronRightSmall" slot="footer">
          Details
        </IxButton>
      </div>
    </IxTile>
  </div>
</template>
