// packages/react-test-app/src/preview-examples/time-input-disabled.tsx
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxTimeInput } from '@irisieason/ix-react';

export default () => {
  return <IxTimeInput disabled></IxTimeInput>;
};

// packages/vue-test-app/src/preview-examples/time-input-disabled.vue
<!--
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxTimeInput } from '@irisieason/ix-vue';
</script>

<template>
  <IxTimeInput disabled></IxTimeInput>
</template>
