// packages/react-test-app/src/preview-examples/timepicker.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxTimePicker } from '@irisieason/ix-react';

export default () => {
  return <IxTimePicker />;
};

// packages/vue-test-app/src/preview-examples/timepicker.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxTimePicker } from '@irisieason/ix-vue';
</script>

<template>
  <IxTimePicker />
</template>
