// packages/angular-standalone-test-app/src/preview-examples/time-input-label.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';
import {
  IxTimeInput,
  IxTimeValueAccessorDirective,
} from '@irisieason/ix-angular/standalone';

@Component({
  selector: 'app-example',
  imports: [IxTimeInput, IxTimeValueAccessorDirective],
  templateUrl: './time-input-label.html',
})
export default class TimeInputLabel {}

// packages/vue-test-app/src/preview-examples/time-input-label.vue
<!--
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxTimeInput } from '@irisieason/ix-vue';
</script>

<template>
  <IxTimeInput
    label="Time"
    name="time"
    helper-text="Some helper text"
  ></IxTimeInput>
</template>
