// packages/react-test-app/src/preview-examples/toggle-checked.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxToggle } from '@irisieason/ix-react';

export default () => {
  return <IxToggle checked />;
};

// packages/vue-test-app/src/preview-examples/toggle-checked.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxToggle } from '@irisieason/ix-vue';
</script>

<template>
  <IxToggle checked />
</template>
