// packages/react-test-app/src/preview-examples/button-danger-outline.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import './button-danger-outline.scoped.css';

import { IxButton } from '@irisieason/ix-react';

export default () => {
  return (
    <>
      <IxButton variant="danger-secondary">
        Button
      </IxButton>
      <IxButton disabled variant="danger-secondary">
        Button
      </IxButton>
    </>
  );
};

// packages/angular-standalone-test-app/src/preview-examples/button-danger-outline.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';
import { IxButton } from '@irisieason/ix-angular/standalone';

@Component({
  selector: 'app-example',
  imports: [IxButton],
  templateUrl: './button-danger-outline.html',
  styleUrls: ['./button-danger-outline.css'],
})
export default class Buttons {}
