// packages/react-test-app/src/preview-examples/checkbox-indeterminate.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { useLayoutEffect, useRef } from 'react';

export default () => {
  const ref = useRef<HTMLInputElement>(null);

  useLayoutEffect(() => {
    const element = ref.current;

    if (element) {
      element.indeterminate = true;
    }
  }, []);

  return (
    <>
      <input
        className="ix-form-control"
        type="checkbox"
        id="checkbox_01"
        ref={ref}
      />
      <label className="ix-form-label" htmlFor="checkbox_01">
        Simple checkbox
      </label>
    </>
  );
};

// packages/angular-standalone-test-app/src/preview-examples/checkbox-indeterminate.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  selector: 'app-example',
  template: `
    <div>
      <input type="checkbox" id="checkbox_01" [indeterminate]="true" />
      <label for="checkbox_01">Simple checkbox</label>
    </div>
  `,
})
export default class CheckboxIndeterminate {}
