// packages/react-test-app/src/preview-examples/date-input-min-max-date.tsx
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxDateInput } from '@irisieason/ix-react';

export default () => {
  return (
    <IxDateInput
      minDate="2025/07/06"
      maxDate="2025/07/14"
      value="2025/07/07"
    ></IxDateInput>
  );
};

// packages/angular-standalone-test-app/src/preview-examples/date-input-min-max-date.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';
import {
  IxDateInput,
  IxDateValueAccessorDirective,
} from '@irisieason/ix-angular/standalone';

@Component({
  selector: 'app-example',
  imports: [IxDateInput, IxDateValueAccessorDirective],
  templateUrl: './date-input-min-max-date.html',
})
export default class DateInputMinMaxDate {}
