// packages/react-test-app/src/preview-examples/form-checkbox-disabled.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxCheckbox } from '@irisieason/ix-react';

export default () => {
  return (
    <IxCheckbox label="I agree everything" name="agreed" disabled></IxCheckbox>
  );
};

// packages/angular-standalone-test-app/src/preview-examples/form-checkbox-disabled.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';
import {
  IxCheckbox,
  IxBooleanValueAccessorDirective,
} from '@irisieason/ix-angular/standalone';

@Component({
  selector: 'app-example',
  imports: [IxCheckbox, IxBooleanValueAccessorDirective],
  templateUrl: `./form-checkbox-disabled.html`,
})
export default class FormCheckboxDisabled {}
