// packages/react-test-app/src/preview-examples/input-legacy-readonly.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

export default () => {
  return (
    <form className="needs-validation">
      <input
        defaultValue="Some example text"
        placeholder="Enter text here"
        type="text"
        readOnly
        className='ix-form-control'
      />
    </form>
  );
};

// packages/angular-standalone-test-app/src/preview-examples/input-legacy-readonly.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  selector: 'app-example',
  template: `
    <form class="needs-validation">
      <input
        value="Some example text"
        placeholder="Enter text here"
        type="text"
        readonly
      />
    </form>
  `,
})
export default class InputLegacyReadonly {}
