// packages/react-test-app/src/preview-examples/key-value.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxKeyValue } from '@irisieason/ix-react';

export default () => {
  return <IxKeyValue label="Label" value="Value"></IxKeyValue>;
};

// packages/angular-standalone-test-app/src/preview-examples/key-value.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';
import { IxKeyValue } from '@irisieason/ix-angular/standalone';

@Component({
  selector: 'app-example',
  imports: [IxKeyValue],
  template: `<ix-key-value label="Label" value="Value"></ix-key-value>`,
})
export default class KeyValue {}
