// packages/react-test-app/src/preview-examples/link-button-disabled.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxLinkButton } from '@irisieason/ix-react';

export default () => {
  return (
    <IxLinkButton url="https://ix.siemens.io/" disabled>
      Link text
    </IxLinkButton>
  );
};

// packages/angular-standalone-test-app/src/preview-examples/link-button-disabled.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';
import { IxLinkButton } from '@irisieason/ix-angular/standalone';

@Component({
  selector: 'app-example',
  imports: [IxLinkButton],
  template: `
    <ix-link-button url="https://ix.siemens.io/" disabled>
      Link text
    </ix-link-button>
  `,
})
export default class LinkButtonDisabled {}
