// packages/react-test-app/src/preview-examples/radio.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxRadio } from '@irisieason/ix-react';

export default () => {
  return (
    <IxRadio label="256GB SSD storage" value="1" name="storage-256gb"></IxRadio>
  );
};

// packages/angular-standalone-test-app/src/preview-examples/radio.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';
import {
  IxRadio,
  IxRadioValueAccessorDirective,
} from '@irisieason/ix-angular/standalone';

@Component({
  selector: 'app-example',
  imports: [IxRadio, IxRadioValueAccessorDirective],
  templateUrl: './radio.html',
})
export default class Radio {}
