// packages/react-test-app/src/preview-examples/time-input-with-slots.tsx
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxTimeInput, IxIcon, IxTypography } from '@siemens/ix-react';
import { iconBulb } from '@irisieason/ix-icons/icons';

export default () => {
  return (
    <IxTimeInput>
      <IxIcon name={iconBulb} slot="start" size="16"></IxIcon>
      <IxTypography slot="end">Slot</IxTypography>
    </IxTimeInput>
  );
};

// packages/angular-standalone-test-app/src/preview-examples/time-input-with-slots.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';
import {
  IxTimeInput,
  IxIcon,
  IxTypography,
  IxTimeValueAccessorDirective,
} from '@irisieason/ix-angular/standalone';

@Component({
  selector: 'app-example',
  imports: [IxTimeInput, IxIcon, IxTypography, IxTimeValueAccessorDirective],
  templateUrl: './time-input-with-slots.html',
})
export default class TimeInputWithSlots {}
