// packages/react-test-app/src/preview-examples/upload.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxUpload } from '@irisieason/ix-react';

export default () => {
  return <IxUpload />;
};

// packages/angular-standalone-test-app/src/preview-examples/upload.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';
import { IxUpload } from '@irisieason/ix-angular/standalone';

@Component({
  selector: 'app-example',
  imports: [IxUpload],
  template: ` <ix-upload></ix-upload> `,
})
export default class Upload {}
