// packages/react-test-app/src/preview-examples/button-grey-secondary.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import './button-grey-secondary.scoped.css';

import { IxButton } from '@siemens/ix-react';

export default () => {
  return (
    <>
      <IxButton variant="subtle-secondary">
        Button
      </IxButton>
      <IxButton disabled variant="subtle-secondary">
        Button
      </IxButton>
    </>
  );
};

// packages/angular-test-app/src/preview-examples/button-grey-secondary.ts
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  standalone: false,
  selector: 'app-example',
  template: `
    <ix-button variant="subtle-secondary"> Button </ix-button>
    <ix-button disabled variant="subtle-secondary"> Button </ix-button>
  `,
  styleUrls: ['./button-grey-secondary.css'],
})
export default class Buttons {}
