// packages/react-test-app/src/preview-examples/checkbox.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

export default () => {
  return (
    <>
      <div style={{ marginBottom: '1rem' }}>
        <input className="ix-form-control" type="checkbox" id="checkbox_01" />
        <label className="ix-form-label" htmlFor="checkbox_01">
          Simple checkbox
        </label>
      </div>

      <div>
        <input
          className="ix-form-control"
          type="checkbox"
          id="checkbox_02"
          disabled
        />
        <label className="ix-form-label" htmlFor="checkbox_02">
          Disabled checkbox
        </label>
      </div>
    </>
  );
};

// packages/angular-test-app/src/preview-examples/checkbox.ts
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  standalone: false,
  selector: 'app-example',
  template: `
    <div style="margin-bottom: 1rem">
      <input class="ix-form-control" type="checkbox" id="checkbox_01" />
      <label class="ix-form-label" for="checkbox_01">Simple checkbox</label>
    </div>

    <div>
      <input
        class="ix-form-control"
        type="checkbox"
        id="checkbox_02"
        disabled
      />
      <label class="ix-form-label" for="checkbox_02">Disabled checkbox</label>
    </div>
  `,
})
export default class Checkbox {}
