// packages/react-test-app/src/preview-examples/input-legacy.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

export default () => {
  return (
    <form className="needs-validation">
      <input
        defaultValue="Some example text"
        placeholder="Enter text here"
        type="text"
        className="ix-form-control"
      />
    </form>
  );
};

// packages/angular-test-app/src/preview-examples/input-legacy.ts
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  standalone: false,
  selector: 'app-example',
  template: `
    <form class="needs-validation">
      <input
        value="Some example text"
        placeholder="Enter text here"
        type="text"
        class="ix-form-control"
      />
    </form>
  `,
})
export default class InputLegacy {}
