// packages/react-test-app/src/preview-examples/number-input-label.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxNumberInput } from '@siemens/ix-react';

export default () => {
  return (
    <IxNumberInput
      label="Some label"
      helperText="Some helper text"
    ></IxNumberInput>
  );
};

// packages/angular-test-app/src/preview-examples/number-input-label.ts
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  standalone: false,
  selector: 'app-example',
  templateUrl: './number-input-label.html',
})
export default class NumberInputLabel {}
