// packages/react-test-app/src/preview-examples/pagination.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxPagination } from '@siemens/ix-react';

export default () => {
  return (
    <>
      <IxPagination count={100}></IxPagination>
    </>
  );
};

// packages/angular-test-app/src/preview-examples/pagination.ts
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  standalone: false,
  selector: 'app-example',
  template: ` <ix-pagination count="100"></ix-pagination> `,
})
export default class Pagination {}
