// packages/react-test-app/src/preview-examples/spinner-large.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxSpinner } from '@siemens/ix-react';

export default () => {
  return <IxSpinner size="large"></IxSpinner>;
};

// packages/angular-test-app/src/preview-examples/spinner-large.ts
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  standalone: false,
  selector: 'app-example',
  template: ` <ix-spinner size="large"></ix-spinner> `,
})
export default class SpinnerLarge {}
