// packages/core/src/components/tile/tile.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component, Element, h, Host, Prop, State } from '@stencil/core';

@Component({
  tag: 'ix-tile',
  styleUrl: 'tile.scss',
  shadow: true,
})
export class Tile {
  @Element() hostElement!: HTMLIxTileElement;

  /**
   * Size of the tile - one of 'small', 'medium' or 'large'
   */
  @Prop() size: 'small' | 'medium' | 'big' = 'medium';

  @State() hasHeaderSlot: boolean = false;
  @State() hasFooterSlot: boolean = false;

  handleHeaderSlotChange() {
    this.hasHeaderSlot = !!this.hostElement.querySelector('[slot="header"]');
  }

  handleFooterSlotChange() {
    this.hasFooterSlot = !!this.hostElement.querySelector('[slot="footer"]');
  }

  render() {
    return (
      <Host
        class={{
          'tile-small': this.size === 'small',
          'tile-medium': this.size === 'medium',
          'tile-big': this.size === 'big',
        }}
      >
        <div
          class={{
            'tile-header': true,
            'has-content': this.hasHeaderSlot,
          }}
        >
          <slot
            name="header"
            onSlotchange={() => this.handleHeaderSlotChange()}
          ></slot>
        </div>
        <div class="tile-subheader">
          <slot name="subheader"></slot>
        </div>
        <div class="tile-content">
          <slot></slot>
        </div>
        <div
          class={{
            'tile-footer': true,
            'has-content': this.hasFooterSlot,
          }}
        >
          <slot
            name="footer"
            onSlotchange={() => this.handleFooterSlotChange()}
          ></slot>
        </div>
      </Host>
    );
  }
}

// packages/angular-test-app/src/preview-examples/tile.ts
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  standalone: false,
  selector: 'app-example',
  template: `
    <ix-tile size="small">92.8 °C</ix-tile>

    <ix-tile size="medium">
      <div slot="header">Tile header</div>
      <div class="text-l">92.8 °C</div>
    </ix-tile>

    <ix-tile size="big">
      <div class="tile-header" slot="header">
        Tile header
        <ix-icon-button variant="tertiary" icon="context-menu"></ix-icon-button>
      </div>
      <div slot="subheader">Temperature</div>
      <div
        style="
        display: flex;
        flex-direction: column;
        height: 100%;
        align-items: flex-end;
        justify-content: space-between;
      "
      >
        <span>92.8 °C</span>
      </div>
      <div class="tile-footer" slot="footer">
        <ix-button variant="tertiary" icon="chevron-right-small" slot="footer">
          Details
        </ix-button>
      </div>
    </ix-tile>
  `,
  styleUrls: ['./tile.css'],
})
export default class Tile {}
