// packages/react-test-app/src/preview-examples/toggle-custom-label.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxToggle } from '@siemens/ix-react';

export default () => {
  return <IxToggle text-off="Offline" text-on="Online"></IxToggle>;
};

// packages/angular-test-app/src/preview-examples/toggle-custom-label.ts
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  standalone: false,
  selector: 'app-example',
  template: ` <ix-toggle text-off="Offline" text-on="Online"></ix-toggle> `,
})
export default class ToggleCustomLabel {}
