// packages/vue-test-app/src/preview-examples/avatar-image.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxAvatar } from '@irisieason/ix-vue';
</script>

<template>
  <IxAvatar
    image="https://www.gravatar.com/avatar/00000000000000000000000000000000"
  ></IxAvatar>
</template>

// packages/react-test-app/src/preview-examples/avatar-image.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxAvatar } from '@irisieason/ix-react';

export default () => {
  return (
    <IxAvatar image="https://www.gravatar.com/avatar/00000000000000000000000000000000"></IxAvatar>
  );
};
