// packages/angular-standalone-test-app/src/preview-examples/avatar-initials.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';
import { IxAvatar } from '@irisieason/ix-angular/standalone';

@Component({
  selector: 'app-example',
  imports: [IxAvatar],
  template: ` <ix-avatar initials="JD"></ix-avatar> `,
})
export default class AvatarInitials {}

// packages/react-test-app/src/preview-examples/avatar-initials.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxAvatar } from '@irisieason/ix-react';

export default () => {
  return <IxAvatar initials="JD"></IxAvatar>;
};
