// packages/vue-test-app/src/preview-examples/button-ghost.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxButton } from '@irisieason/ix-vue';
</script>

<style scoped src="./button-ghost.css"></style>

<template>
  <IxButton variant="tertiary"> Button </IxButton>
  <IxButton variant="tertiary" disabled> Button </IxButton>
</template>

// packages/react-test-app/src/preview-examples/button-ghost.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import './button-ghost.scoped.css';

import { IxButton } from '@irisieason/ix-react';

export default () => {
  return (
    <>
      <IxButton variant="tertiary">
        Button
      </IxButton>
      <IxButton variant="tertiary" disabled>
        Button
      </IxButton>
    </>
  );
};
