// packages/angular-test-app/src/preview-examples/button-danger-ghost.ts
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  standalone: false,
  selector: 'app-example',
  templateUrl: './button-danger-ghost.html',
})
export default class Buttons {}

// packages/react-test-app/src/preview-examples/button-danger-ghost.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import './button-danger-ghost.scoped.css';

import { IxButton } from '@siemens/ix-react';

export default () => {
  return (
    <>
      <IxButton variant="subtle-tertiary">
        Button
      </IxButton>
      <IxButton disabled variant="subtle-tertiary">
        Button
      </IxButton>
    </>
  );
};
