// packages/vue-test-app/src/preview-examples/date-input-readonly.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxDateInput } from '@irisieason/ix-vue';
</script>

<template>
  <IxDateInput value="1970/01/01" readonly></IxDateInput>
</template>

// packages/react-test-app/src/preview-examples/date-input-readonly.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxDateInput } from '@irisieason/ix-react';

export default () => {
  return <IxDateInput value="1970/01/01" readonly></IxDateInput>;
};
