// packages/angular-test-app/src/preview-examples/datetimepicker.ts
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  standalone: false,
  selector: 'app-example',
  template: `<ix-datetime-picker></ix-datetime-picker>`,
})
export default class Datetimepicker {}

// packages/react-test-app/src/preview-examples/datetimepicker.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxDatetimePicker } from '@siemens/ix-react';

export default () => {
  return <IxDatetimePicker />;
};
