// packages/vue-test-app/src/preview-examples/datepicker-range.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxDatePicker } from '@irisieason/ix-vue';
</script>

<template>
  <IxDatePicker from="2022/12/15" to="2022/12/24" />
</template>

// packages/react-test-app/src/preview-examples/datepicker-range.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxDatePicker } from '@irisieason/ix-react';

export default () => {
  return <IxDatePicker from="2022/12/15" to="2022/12/24" />;
};
