// packages/angular-test-app/src/preview-examples/date-input-with-slots.ts
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  standalone: false,
  selector: 'app-example',
  templateUrl: './date-input-with-slots.html',
})
export default class DateInputWithSlots {}

// packages/react-test-app/src/preview-examples/date-input-with-slots.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxDateInput, IxIcon, IxTypography } from '@irisieason/ix-react';
import { iconBulb } from '@irisieason/ix-icons/icons';

export default () => {
  return (
    <IxDateInput value="1970/01/01">
      <IxIcon name={iconBulb} slot="start" size="16"></IxIcon>
      <IxTypography slot="end">Slot</IxTypography>
    </IxDateInput>
  );
};
