// packages/angular-standalone-test-app/src/preview-examples/divider.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';
import { IxDivider } from '@irisieason/ix-angular/standalone';

@Component({
  selector: 'app-example',
  imports: [IxDivider],
  template: ` <ix-divider></ix-divider> `,
})
export default class Divider {}

// packages/react-test-app/src/preview-examples/divider.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxDivider } from '@irisieason/ix-react';

export default () => {
  return (
    <>
      <IxDivider></IxDivider>
    </>
  );
};
