// packages/vue-test-app/src/preview-examples/drawer-full-height.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxButton, IxDrawer } from '@irisieason/ix-vue';
import { ref } from 'vue';

const show = ref(false);
</script>

<template>
  <IxDrawer
    closeOnClickOutside
    fullHeight
    :show="show"
    @drawerClose="show = false"
  >
    <span>Some content of drawer</span>
  </IxDrawer>
  <IxButton @click="show = !show">Toggle drawer</IxButton>
</template>

// packages/react-test-app/src/preview-examples/drawer-full-height.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxButton, IxDrawer } from '@irisieason/ix-react';
import { useState } from 'react';

export default () => {
  const [show, setShow] = useState(false);

  return (
    <>
      <IxDrawer
        closeOnClickOutside={true}
        fullHeight={true}
        show={show}
        onDrawerClose={() => setShow(false)}
      >
        <span>Some content of drawer</span>
      </IxDrawer>
      <IxButton onClick={() => setShow(!show)}>Toggle drawer</IxButton>
    </>
  );
};
