// packages/vue-test-app/src/preview-examples/dropdown-quick-actions.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import {
  iconBulb,
  iconCut,
  iconDocument,
  iconStar,
  iconTrashcan,
} from '@irisieason/ix-icons/icons';
import {
  IxButton,
  IxDivider,
  IxDropdown,
  IxDropdownItem,
  IxDropdownQuickActions,
  IxIconButton,
} from '@irisieason/ix-vue';
</script>

<template>
  <div>
    <IxButton id="iconTriggerId">Open</IxButton>
    <IxDropdown trigger="iconTriggerId">
      <IxDropdownQuickActions>
        <IxIconButton variant="tertiary" :icon="iconCut"></IxIconButton>
        <IxIconButton variant="tertiary" :icon="iconBulb"></IxIconButton>
        <IxIconButton variant="tertiary" :icon="iconTrashcan"></IxIconButton>
      </IxDropdownQuickActions>

      <IxDivider></IxDivider>

      <IxDropdownItem :icon="iconStar" label="Item 1"></IxDropdownItem>
      <IxDropdownItem :icon="iconDocument" label="Item 2"></IxDropdownItem>
      <IxDropdownItem :icon="iconBulb" label="Item 3"></IxDropdownItem>
    </IxDropdown>
  </div>
</template>

// packages/react-test-app/src/preview-examples/dropdown-quick-actions.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import {
  iconBulb,
  iconCut,
  iconDocument,
  iconStar,
  iconTrashcan,
} from '@irisieason/ix-icons/icons';
import {
  IxButton,
  IxDivider,
  IxDropdown,
  IxDropdownItem,
  IxDropdownQuickActions,
  IxIconButton,
} from '@siemens/ix-react';

export default () => {
  return (
    <>
      <IxButton id="iconTriggerId">Open</IxButton>
      <IxDropdown trigger="iconTriggerId">
        <IxDropdownQuickActions>
          <IxIconButton variant="tertiary" icon={iconCut}></IxIconButton>
          <IxIconButton variant="tertiary" icon={iconBulb}></IxIconButton>
          <IxIconButton variant="tertiary" icon={iconTrashcan}></IxIconButton>
        </IxDropdownQuickActions>

        <IxDivider></IxDivider>

        <IxDropdownItem icon={iconStar} label="Item 1"></IxDropdownItem>
        <IxDropdownItem icon={iconDocument} label="Item 2"></IxDropdownItem>
        <IxDropdownItem icon={iconBulb} label="Item 3"></IxDropdownItem>
      </IxDropdown>
    </>
  );
};
