// packages/angular-test-app/src/preview-examples/form-checkbox.ts
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  standalone: false,
  selector: 'app-example',
  templateUrl: `./form-checkbox.html`,
})
export default class FormCheckbox {}

// packages/react-test-app/src/preview-examples/form-checkbox.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxCheckbox } from '@siemens/ix-react';

export default () => {
  return (
    <IxCheckbox label="I agree everything" name="agreed"></IxCheckbox>
  );
};
