// packages/vue-test-app/src/preview-examples/form-checkbox-disabled.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang='ts'>
import { IxCheckbox } from '@irisieason/ix-vue';
</script>

<template>
  <IxCheckbox label="I agree everything" name="agreed" disabled></IxCheckbox>
</template>

// packages/react-test-app/src/preview-examples/form-checkbox-disabled.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxCheckbox } from '@irisieason/ix-react';

export default () => {
  return (
    <IxCheckbox label="I agree everything" name="agreed" disabled></IxCheckbox>
  );
};
