// packages/angular-standalone-test-app/src/preview-examples/input-disabled.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';
import {
  IxInput,
  IxTextValueAccessorDirective,
} from '@irisieason/ix-angular/standalone';

@Component({
  selector: 'app-example',
  imports: [IxInput, IxTextValueAccessorDirective],
  templateUrl: './input-disabled.html',
})
export default class InputDisabled {}

// packages/react-test-app/src/preview-examples/input-disabled.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxInput } from '@irisieason/ix-react';

export default () => {
  return (
    <IxInput
      placeholder="Some placeholder"
      value="Some example text"
      disabled
    ></IxInput>
  );
};
