// packages/vue-test-app/src/preview-examples/key-value-list-striped.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxKeyValue, IxKeyValueList } from '@irisieason/ix-vue';
</script>

<template>
  <IxKeyValueList striped>
    <IxKeyValue label="Label" labelPosition="left" value="Value"></IxKeyValue>
    <IxKeyValue label="Label" labelPosition="left" value="Value"></IxKeyValue>
    <IxKeyValue label="Label" labelPosition="left" value="Value"></IxKeyValue>
  </IxKeyValueList>
</template>

// packages/react-test-app/src/preview-examples/key-value-list-striped.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxKeyValue, IxKeyValueList } from '@irisieason/ix-react';

export default () => {
  return (
    <IxKeyValueList striped={true}>
      <IxKeyValue label="Label" labelPosition="left" value="Value"></IxKeyValue>
      <IxKeyValue label="Label" labelPosition="left" value="Value"></IxKeyValue>
      <IxKeyValue label="Label" labelPosition="left" value="Value"></IxKeyValue>
    </IxKeyValueList>
  );
};
