// packages/vue-test-app/src/preview-examples/key-value-with-label-left.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxKeyValue } from '@irisieason/ix-vue';
</script>

<template>
  <IxKeyValue label="Label" labelPosition="left" value="Value"></IxKeyValue>
</template>

// packages/react-test-app/src/preview-examples/key-value-with-label-left.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxKeyValue } from '@irisieason/ix-react';

export default () => {
  return (
    <IxKeyValue label="Label" labelPosition="left" value="Value"></IxKeyValue>
  );
};
