// packages/vue-test-app/src/preview-examples/number-input-stepper-button.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxNumberInput } from '@irisieason/ix-vue';
</script>

<template>
  <IxNumberInput
    :value="0"
    show-stepper-buttons
  ></IxNumberInput>
</template>

// packages/react-test-app/src/preview-examples/number-input-stepper-button.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxNumberInput } from '@irisieason/ix-react';

export default () => {
  return <IxNumberInput value={0} showStepperButtons></IxNumberInput>;
};
