// packages/vue-test-app/src/preview-examples/pagination-advanced.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxPagination } from '@irisieason/ix-vue';
</script>

<template>
  <IxPagination advanced show-item-count :count="100"></IxPagination>
</template>

// packages/react-test-app/src/preview-examples/pagination-advanced.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxPagination } from '@irisieason/ix-react';

export default () => {
  return (
    <>
      <IxPagination advanced showItemCount count={100}></IxPagination>
    </>
  );
};
