// packages/angular-standalone-test-app/src/preview-examples/push-card.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';
import { IxPushCard } from '@irisieason/ix-angular/standalone';

@Component({
  selector: 'app-example',
  imports: [IxPushCard],
  templateUrl: './push-card.html',
})
export default class PushCard {}

// packages/react-test-app/src/preview-examples/push-card.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { iconBulb } from '@irisieason/ix-icons/icons';
import { IxPushCard } from '@siemens/ix-react';

export default () => {
  return (
    <IxPushCard
      icon={iconBulb}
      notification="99"
      heading="Heading content"
      subheading="Subheading"
      variant="outline"
    >
      <table className="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">Handle</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">1</th>
            <td>Mark</td>
            <td>Otto</td>
            <td>@mdo</td>
          </tr>
          <tr>
            <th scope="row">2</th>
            <td>Jacob</td>
            <td>Thornton</td>
            <td>@fat</td>
          </tr>
          <tr>
            <th scope="row">3</th>
            <td colSpan={2}>Larry the Bird</td>
            <td>@twitter</td>
          </tr>
        </tbody>
      </table>
    </IxPushCard>
  );
};
