// packages/angular-test-app/src/preview-examples/radio.ts
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  standalone: false,
  selector: 'app-example',
  templateUrl: './radio.html',
})
export default class Radio {}

// packages/react-test-app/src/preview-examples/radio.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxRadio } from '@siemens/ix-react';

export default () => {
  return (
    <IxRadio label="256GB SSD storage" value="1" name="storage-256gb"></IxRadio>
  );
};
