// packages/angular-standalone-test-app/src/preview-examples/toggle-button-secondary-ghost.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';
import { IxToggleButton } from '@irisieason/ix-angular/standalone';

@Component({
  selector: 'app-example',
  imports: [IxToggleButton],
  template: `
    <ix-toggle-button variant="tertiary"> Normal</ix-toggle-button>
    <ix-toggle-button variant="tertiary" pressed> Pressed</ix-toggle-button>
    <ix-toggle-button variant="tertiary" disabled> Disabled</ix-toggle-button>
    <ix-toggle-button variant="tertiary" disabled loading> Loading</ix-toggle-button>
  `,
  styleUrls: ['./toggle-button-secondary-ghost.css'],
})
export default class Buttons {}

// packages/react-test-app/src/preview-examples/toggle-button-secondary-ghost.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import './toggle-button-secondary-ghost.scoped.css';

import { IxToggleButton } from '@irisieason/ix-react';

export default () => {
  return (
    <>
      <IxToggleButton variant="tertiary">Normal</IxToggleButton>
      <IxToggleButton variant="tertiary" pressed>
        Pressed
      </IxToggleButton>
      <IxToggleButton variant="tertiary" disabled>
        Disabled
      </IxToggleButton>
      <IxToggleButton variant="tertiary" disabled loading>
        Loading
      </IxToggleButton>
    </>
  );
};
